name: ad-hoc

on:
  issue_comment:
    types: [created]

permissions:
  contents: read

jobs:
  # Trigger ad-hoc deploy only if "/deploy" comment is left on the pull request.
  # Wait for the build to complete first before triggering with a comment.
  ad-hoc:
    runs-on: ubuntu-latest
    steps:
      - name: Show head_ref
        run: echo ${{ github.head_ref }}

      - name: Show ref_name
        run: echo ${{ github.ref_name }}
      
      - name: Show github.base_ref
        run: echo ${{ github.base_ref }}
